### ISSUE TITLE
Sync action silently fails with a TypeError & UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by ianjevans** [readmeio/github-readme-api-sync#23]
The action appears to succeed with a green check, but if you examine the output it is failing with a TypeError.
```
Run readmeio/github-readme-sync@2.0.0
(node:2493) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of undefined
    at /home/runner/work/_actions/readmeio/github-readme-sync/2.0.0/main.js:95:28
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2493) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2493) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This was is the relevant section of the action config:
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: readmeio/github-readme-sync@2.0.0
        with:
          readme-oas-key: xxxx
           
          # OPTIONAL CONFIG, use if necessary
          oas-file-path: './dev-ops-api/api/swagger.yaml'
          # api-version: 'v1.0.0'
```
