### ISSUE TITLE
Can't Create New Version

### ISSUE THREAD

**Issue by cooperpellaton** [readmeio/github-readme-api-sync#43]
I assume this is a limitation of the API, but it's not possible to create a new version on upload. For example, I am trying to follow an automated [calver](https://calver.org/) upload on a push to a branch. Here's a sample of what I'm doing for reproducibility:
```yaml
name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
      - main
jobs:
  document:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "14.x"
      - name: install dependencies
        run: npm i swagger-inline
      - name: set version by calver
        id: ver
        run: |
          echo ::set-output name=VERSION::$(date +"%Y.%m.%d")
      - name: generate documentation
        run: npx swagger-inline */*.js --base baseSwagger.yaml --scope public > swagger.yaml
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: qTDbntRax07zYdWpdXUaaBhQePkZK2wO:5f97763f7abfc702cf63d010
          api-version: ${{steps.ver.outputs.VERSION}}
          oas-file-path: swagger.yaml
```

So I'm dynamically setting the `api-version` based on the output of date which will be format `YYYY-MM-DD`. However, this fails as the version does _not_ already exist on readme.io. 

Further, I've tried using [`yq`](https://github.com/mikefarah/yq) to set the value directly in the OAS, but that similarly fails. I think, at the least, it should be documented that the specified `api-version` must already exist before upload.

An example of the `yq` command:
```bash
yq w -i baseSwagger.yaml info.version $(date +"%Y.%m.%d")
```
