### ISSUE TITLE
publish Guides

### ISSUE THREAD

**Issue by benjamine** [readmeio/github-readme-api-sync#74]
I'm wondering if this is the right tool for this job, but would be interesting if besides API reference,
we could also sync markdown files in the github repo with the "Guides" in our readmeio.
Is this something you would consider for this tool?

**Comment by kanadgupta** [comment]
Hi @benjamine, thanks for reaching out! We have no plans to add that support to this tool. Fortunately, [`rdme`](https://github.com/readmeio/rdme) should work well here, with a YAML file that looks something similar to this:

```yml
steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v2
  with:
    node-version: '14'
    cache: 'npm'
- run: npm install # you'll need to include `rdme` in your project's dev dependencies
- run: npx rdme docs <path to markdown folder> --key=<your project API key> --version=<your project version>
```
[Feel free to reach out to our support team](mailto:support@readme.io) if you have any questions!

Best,

-Kanad
